import os
import traceback
import uuid
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from .api import router as api_router
from .api.response.response import error, http_exception, ok
from .api.v1.openai import close_http_client, get_http_client
from .logger import log

GIT_REV_PATH = "/etc/.GIT_REV"

# Status codes where we preserve the original HTTPException detail message
# These are client errors where the detail is controlled by our code and safe to expose
PRESERVE_DETAIL_STATUS_CODES = {
    413,  # Payload Too Large - includes max size info
}

# Safe detail message prefixes that can be preserved for any status code
# These are messages generated by our application code, not external exceptions
SAFE_DETAIL_PREFIXES = (
    "Request body too large",
    "Signing address not found",
    "Maximum",
)


def _read_git_rev() -> str:
    """Read git revision from /etc/.GIT_REV file."""
    try:
        if os.path.exists(GIT_REV_PATH):
            with open(GIT_REV_PATH, "r") as f:
                return f.read().strip()
    except Exception:
        pass
    return "unknown"


GIT_REV = _read_git_rev()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage application lifespan - startup and shutdown."""
    # Startup: initialize the HTTP client pool
    log.info("Initializing HTTP client pool...")
    get_http_client()
    log.info("HTTP client pool initialized")
    yield
    # Shutdown: close the HTTP client pool
    log.info("Closing HTTP client pool...")
    await close_http_client()
    log.info("HTTP client pool closed")


app = FastAPI(lifespan=lifespan)


class RequestIDMiddleware(BaseHTTPMiddleware):
    """
    Middleware that generates a unique request ID for each request.

    The request ID is:
    - Stored in request.state.request_id for use in handlers
    - Added to response headers as X-Request-ID
    - Used in error responses for debugging/support purposes
    """

    async def dispatch(self, request: Request, call_next):
        # Generate or use existing request ID from header
        request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())
        request.state.request_id = request_id

        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        return response


# Add middleware before routes
app.add_middleware(RequestIDMiddleware)
app.include_router(api_router)


def get_request_id(request: Request) -> str:
    """Safely get request ID from request state."""
    return getattr(request.state, "request_id", None) or str(uuid.uuid4())


@app.get("/")
async def root():
    return ok()


@app.get("/version")
async def show_version():
    """Return version information for this vllm-proxy instance."""
    ver = {"version": GIT_REV, "type": "proxy"}
    return JSONResponse(content=ver)


def _is_safe_detail(detail: str) -> bool:
    """
    Check if an exception detail message is safe to expose to clients.

    Safe messages are those generated by our application code, not from
    external exceptions that might contain user data.
    """
    if not detail or not isinstance(detail, str):
        return False
    return detail.startswith(SAFE_DETAIL_PREFIXES)


def _get_error_message(exc: HTTPException) -> str:
    """
    Determine the appropriate error message for an HTTPException.

    For certain status codes or safe detail patterns, preserves the original
    detail message. Otherwise, returns a generic message to prevent leaking
    potentially sensitive information.
    """
    # Generic messages for common status codes
    generic_messages = {
        400: "Bad request",
        401: "Unauthorized",
        403: "Forbidden",
        404: "Resource not found",
        429: "Too many requests",
        500: "Internal server error",
    }

    # Safely extract detail string, with fallback for edge cases
    try:
        if isinstance(exc.detail, str):
            detail = exc.detail
        elif exc.detail is None:
            detail = ""
        else:
            detail_str = str(exc.detail)
            detail = detail_str[:500]  # Limit to 500 chars for safety
    except Exception:
        # If detail extraction fails for any reason, use empty string
        # This handles cases where __str__ might raise an exception
        detail = ""

    # If we got an empty detail, return generic message immediately
    if not detail:
        return generic_messages.get(exc.status_code, "An error occurred")

    # Preserve detail for specific status codes where it's always safe
    if exc.status_code in PRESERVE_DETAIL_STATUS_CODES:
        return detail

    # Preserve detail if it matches safe patterns
    if _is_safe_detail(detail):
        return detail

    # Fall back to generic message
    return generic_messages.get(exc.status_code, "An error occurred")


# Custom global error handler
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Handle all uncaught exceptions globally.

    Features:
    - Includes request ID in error responses for debugging/support
    - Preserves safe error details for certain status codes (e.g., 413)
    - Sanitizes potentially sensitive error messages to prevent data leaks

    Note: Error logging is intentionally minimal to prevent leaking user data
    (e.g., request payloads, prompts) that may appear in exception messages
    or tracebacks.
    """
    request_id = get_request_id(request)

    # handle HTTPException
    if isinstance(exc, HTTPException):
        # Log status code and request ID for debugging
        log.error(f"HTTPException [{exc.status_code}] request_id={request_id}")

        message = _get_error_message(exc)

        return http_exception(
            status_code=exc.status_code,
            message=message,
            request_id=request_id,
        )

    # Log only exception type and request ID, not message or traceback
    log.error(f"Unhandled exception [{type(exc).__name__}] request_id={request_id}")
    # Full details available at DEBUG level only for local debugging
    log.debug(f"Exception details: {traceback.format_exc()}")

    return error(
        status_code=500,
        message="Internal server error",
        type="ServerError",
        param=None,
        code=None,
        request_id=request_id,
    )
